### ISSUE TITLE
Hidden Folders

### ISSUE THREAD

**Issue by carelessproperty** [lachlan-00/rb-fileorganizer#15]
Some albums start with a ".", this causes the folder to be hidden when the organizer is used. I'm guessing that this also applied to other information (ie artist, song name, etc.)

I was using the version where adcebf4e9c3f61a9a3de0415c478a5d9f23bc160 is the last commit.

Information from fileorganizer.log:
```
Britney Spears - ...Baby One More Time - 08:59:07 AM
    IN:    /home/carelessproperty/Music/Music_on_Windows/Britney Spears/_..Baby One More Time/11 The Beat Goes On.mp3
    OUT:   /home/carelessproperty/Music/Music_on_Windows/Britney Spears/...Baby One More Time/Britney Spears (...Baby One More Time) - 11 - The Beat Goes On.mp3
 ** INFO:  Updating Database:
    OUT:   file:///home/carelessproperty/Music/Music_on_Windows/Britney%20Spears/...Baby%20One%20More%20Time/Britney%20Spears%20(...Baby%20One%20More%20Time)%20-%2011%20-%20The%20Beat%20Goes%20On.mp3
 ** INFO:  Removing empty directory
    /home/carelessproperty/Music/Music_on_Windows/Britney Spears/_..Baby One More Time
```
Settings:
![fileorganizersettings](https://cloud.githubusercontent.com/assets/20501753/16901160/f453b796-4c08-11e6-97f0-e0d9521f9776.png)

**Comment by lachlan-00** [comment]
It's supposed to add an underscore when a full stop is detected. (it used to and looks like it from your log)

does it do this with strip ntfs disabled?

**Comment by carelessproperty** [comment]
Yes, it seems to have the same result:
```
Britney Spears - ...Baby One More Time - 11:36:10 AM
    IN:    /home/kevin/Music/Music_on_Windows/Britney Spears/time/Britney Spears (...Baby One More Time) - 11 - The Beat Goes On.mp3
    OUT:   /home/kevin/Music/Music_on_Windows/Britney Spears/...Baby One More Time/Britney Spears (...Baby One More Time) - 11 - The Beat Goes On.mp3
 ** INFO:  Updating Database:
    OUT:   file:///home/kevin/Music/Music_on_Windows/Britney%20Spears/...Baby%20One%20More%20Time/Britney%20Spears%20(...Baby%20One%20More%20Time)%20-%2011%20-%20The%20Beat%20Goes%20On.mp3
 ** INFO:  Removing empty directory
    /home/kevin/Music/Music_on_Windows/Britney Spears/time
```
![nontfs](https://cloud.githubusercontent.com/assets/20501753/16992706/692fa5c2-4e6e-11e6-8f86-2b39a02f1f3e.png)

**Comment by lachlan-00** [comment]
Thanks, i'll fix this up ASAP. it's been a while but it must have been removed or commented out at some point. (No idea when though.)
