### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by chrisgraham** [lachlan-00/rb-fileorganizer#21]
"make install" will not work, as you have README.md not README.

I have fixed in:
https://github.com/chrisgraham/rb-fileorganizer/commit/b03572c035431370ff155ddf771d8a06f4b7764b

**Comment by lachlan-00** [comment]
make sa pull if you'd like.i haven't been using this for a few years now so any changes you want to make will be good. you can also take over if you want ot maintain this.

**Comment by chrisgraham** [comment]
Want to make me a repository admin? I can't promise to be a proper maintainer, but I'm using this so I want to keep it at least working.

**Comment by lachlan-00** [comment]
Done!
