### ISSUE TITLE
Could not find loader 'python'

### ISSUE THREAD

**Issue by eracle** [lachlan-00/rb-fileorganizer#6]
Fresh installation of:
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

I open rhythmbox from a command line and when I try to enable the plugin it does not appear and the following error is shown to the stderr:

(rhythmbox:5923): libpeas-WARNING **: Could not find loader 'python' for plugin 'fileorganizer'

**Comment by lachlan-00** [comment]
14.04 is using 3.02? (http://packages.ubuntu.com/trusty/rhythmbox)

The current version i'm using is 3.1 and the plugin works fine. I remember there were a few changes around the 3.0-3.03 area where the plugin formats changed slightly.

i won't be supporting anything less than the current version.

The version updated for 2.99+ might help with your older version.
https://github.com/lachlan-00/rb-fileorganizer/tree/af944711ee378ec5b12e1944923deeb9d19a8a31
